// Docusaurus 3.x
//
// CommonJS on purpose. Do not add "type": "module" to package.json and do not switch
// this file to `export default`. With type:module the production build compiles and then
// dies in server-side rendering with "require.resolveWeak is not a function", because the
// server bundle is CommonJS and Node reads it as ESM. scripts/sync-docs.mjs is ESM by
// its own extension and is unaffected.
// Docs-only site. There is no landing page and no blog, because the index is the
// docs sidebar and anything else is a page nobody maintains. The root page at "/" is
// generated by scripts/sync-docs.mjs from the list of repos it pulled.

// DOCS_ORG may be a comma separated list for a personal build. The first owner is the one
// this site belongs to, which is what the URL and the GitHub link should point at.
const { apiConfig } = require("./scripts/api-specs.js");

const ORG = (process.env.DOCS_ORG || process.env.GITHUB_ORG || "your-org")
  .split(",")[0]
  .trim();

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Tech Docs",
  tagline: "How our systems are built and why",
  favicon: "img/favicon.svg",

  // Cloudflare Pages serves the site at the root of its domain, so baseUrl is "/". It was
  // "/docs-site/" for GitHub Pages project sites, which are served from a subpath; leaving
  // that in place makes every asset and internal link resolve one directory too deep and
  // the site 404s at the domain root. Do not restore it without moving back to Pages.
  //
  // url only affects absolute URLs, meaning the sitemap, canonical tags and social cards,
  // so an approximate value never breaks the site. Set the repo variable DOCS_SITE_URL to
  // the custom domain once it exists.
  url: process.env.DOCS_SITE_URL || `https://${ORG}.github.io`,
  baseUrl: process.env.DOCS_BASE_URL || "/docs-site/",   // GitHub Pages project sites serve
  // from /<repo>/. Serving at "/" here makes every asset resolve one directory too high and the
  // site 404s. Change back to "/" only if this moves to Cloudflare Pages or a custom domain root.
  organizationName: ORG,
  projectName: "docs-site",

  // GitHub Pages ignores static/_headers -- that file is a Cloudflare Pages convention --
  // so the "X-Robots-Tag: noindex, nofollow" it sets is silently dropped here. This puts
  // the same instruction in a <meta name="robots"> tag on every page, which every crawler
  // honours, so moving hosts did not quietly opt these docs into Google.
  //
  // Set the repo variable DOCS_INDEXABLE to "1" if you do want them found by search.
  noIndex: process.env.DOCS_INDEXABLE !== "1",

  // Fail the build on a broken internal link. Worth it. Dead links are how a docs
  // site quietly stops being trustworthy.
  onBrokenLinks: "throw",

  // Rspack and SWC instead of webpack and babel. Faster, and it sidesteps the webpack
  // module-concatenation bug that the OpenAPI theme trips over.
  future: {
    v4: { removeLegacyPostBuildHeadAttribute: true },
    faster: true,
  },

  // Moved off the top level. siteConfig.onBrokenMarkdownLinks is deprecated in 3.9+
  // and warns on every build.
  markdown: {
    // Parse .md as CommonMark, .mdx as MDX. The default in Docusaurus 3 runs everything
    // through MDX, which reads `Map<Id, List<Contact>>` in a generated Apex reference page
    // as a JSX tag and fails the build. Any angle bracket in prose is a hazard under MDX.
    // We use no JSX in docs, so this costs nothing.
    format: "detect",
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: "/", // docs at the root, no separate homepage
          sidebarPath: "./sidebars.js",
          // Required by the OpenAPI theme. ApiItem mounts the state the generated endpoint
          // pages need; without it they render as empty panels with a console error.
          // Ordinary docs are unaffected.
          docItemComponent: "@theme/ApiItem",
          // No editUrl here on purpose. sync-docs.mjs stamps custom_edit_url into every
          // page's frontmatter, pointing at the repo the file actually came from. That is
          // the only way the Edit button stays right when a build covers more than one
          // owner, and it also handles repos whose default branch is not main.
          // Real dates. sync-docs.mjs stamps last_update frontmatter from each source
          // repo's git log, which Docusaurus prefers over this repo's history.
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
        },
        blog: false,
        theme: { customCss: "./src/css/custom.css" },
      }),
    ],
  ],

  // API reference. Any repo that commits docs/api/openapi.yaml gets rendered endpoint
  // pages with request and response samples. scripts/api-specs.js finds them after the
  // sync; nothing is listed by hand. `npm run gen-api` turns each spec into pages, and
  // `npm run build` does it for you.
  plugins: [
    ["docusaurus-plugin-openapi-docs", { id: "api", docsPluginId: "default", config: apiConfig() }],
  ],

  // Algolia DocSearch only indexes public sites. This runs the index at build time
  // and ships it with the site, so it works behind auth.
  themes: [
    "docusaurus-theme-openapi-docs",
    [
      "@easyops-cn/docusaurus-search-local",
      {
        hashed: true,
        // REQUIRED because siteConfig.noIndex is on. This plugin skips any page whose
        // HTML carries a robots noindex tag, so noIndex silently emptied the index and
        // every search returned "No results". This opts the local index back in; it has
        // no effect on crawlers, which still see the meta tag and stay away.
        forceIgnoreNoIndex: true,
        indexBlog: false,
        docsRouteBasePath: "/",
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  themeConfig: {
    // Which code samples the API pages offer. Without this the theme shows all 21 of its
    // languages, including Dart, OCaml and Objective-C, which nobody here is calling this
    // API from. Order here is the order of the tabs, and the first one is the default.
    //
    // `variant` picks the library within a language. Full lists:
    //   javascript: Fetch, jQuery, XHR
    //   nodejs:     Axios, Native, Request, Unirest
    //   php:        cURL, Guzzle, HTTP_Request2, pecl_http
    //   python:     Requests, http.client
    //   shell:      Httpie, wget
    // Note that `shell` is Httpie and wget. curl is its own language, not a shell variant.
    languageTabs: [
      { language: "http", logoClass: "http", variant: "HTTP" },
      { language: "shell", logoClass: "shell", variant: "Httpie" },
      { language: "python", logoClass: "python", variant: "Requests" },
      { language: "javascript", logoClass: "javascript", variant: "Fetch" },
      { language: "nodejs", logoClass: "nodejs", variant: "Axios" },
      { language: "php", logoClass: "php", variant: "cURL" },
    ],

    navbar: {
      title: "Tech Docs",
      items: [
        { type: "docSidebar", sidebarId: "main", position: "left", label: "Systems" },
        { href: `https://github.com/${ORG}`, label: "GitHub", position: "right" },
      ],
    },
    footer: { style: "dark", copyright: "Internal use only." },
    colorMode: { respectPrefersColorScheme: true },
  },
};

module.exports = config;
