// One autogenerated sidebar off the docs folder. Because sync-docs.mjs writes a
// _category_.json per repo, each repo becomes its own collapsible section and you
// never have to hand-maintain this file.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
